### PR TITLE
feat: support ".login-panel-dark" CSS for signup/login pages

### PR DESCRIPTION
**Pull request by okatu-loli**
pc demo video:

https://github.com/user-attachments/assets/1a4914ec-10e6-4c66-b8ee-08a0c75ff3de

mobile demo video:

https://github.com/user-attachments/assets/ff0af0d3-ac7a-4f22-b83c-84114722cefb

### CODE REVIEW

**Comment by hsluoyz** [comment]
Can we avoid adding fields and so many lines of code just for supporting dark CSS? Can you just hack it and put the dark CSS into the normal CSS string using a tricky parsing for now?

**Comment by okatu-loli** [comment]
> @okatu-loli Can we avoid adding fields and so many lines of code just for supporting dark CSS? Can you just hack it and put the dark CSS into the normal CSS string using a tricky parsing for now?
> 
> @dacongda

I have no more ideas

**Comment by dacongda** [comment]
we can merge light mode css and dark css in customCss field, and use suffix -dark to draw a differentiate. For example
image
image

**Comment by dacongda** [comment]
base on above discuss, we can use 
image
to specify the css we want to use.

**Comment by hsluoyz** [comment]
@dacongda yes, that's exactly the effect I want. Do some nice trick to put both CSSs into a single edit box. It's too wasting to create two edit boxes just for the dark stuff.

**Comment by okatu-loli** [comment]
pc demo video:

https://github.com/user-attachments/assets/dd318a30-ae6a-4431-9bb7-72e91ef270b8

mobile demo video:

https://github.com/user-attachments/assets/94aab84a-5187-410c-8580-3e868ba62c17

**Review by dacongda — APPROVED** [review]

**Pull request merged**
