### PR TITLE
Add l10n Czech, Slovak language support

### PR DESCRIPTION
**Pull request by feropeterko**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@feropeterko can you also provide translations for your two new languages, with the help like ChatGPT?

**Comment by feropeterko** [comment]
@hsluoyz I'm native Czech speaker, so I want to start with it due to our client's needs. Slovak language is very similar so I added the support and translation Czech-Slovak is not difficult.

**Comment by hsluoyz** [comment]
@feropeterko it has nothing to do with the native language. You can use ChatGPT-like techs to translate any languages. I'm just reocmmending that you have translated all languages that you want to add

**Comment by feropeterko** [comment]
@hsluoyz I know, it was meaned that I can verify translation of both languages. Do you want to translate starting package directly through json files or through Crowdin when the pull request is merged?

**Pull request closed without merging**
