### PR TITLE
feat: fix init data not delete build-in app and org

### PR DESCRIPTION
**Pull request by ladung**
fix: https://github.com/casdoor/casdoor/issues/2925

### CODE REVIEW

**Comment by ladung** [comment]
still error: 
image

**Comment by ladung** [comment]
This commit only work when start casdoor the first time
If I restart casdoor when apply 2 commit above, i have an error:
image

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor/commit/2187310dbc50b85351cb0811808187ea58a0be8b

**Comment by ladung** [comment]
> Replaced by: [2187310](https://github.com/casdoor/casdoor/commit/2187310dbc50b85351cb0811808187ea58a0be8b)

please create tag for this.

**Comment by ladung** [comment]
> This commit only work when start casdoor the first time If I restart casdoor when apply 2 commit above, i have an error: image
> 
> Cannot delete sessionId in DB, seems to be corrupted by the `beego` version. Please update version to 2.x.x

@hsluoyz  please consider this error!

**Comment by hsluoyz** [comment]
@ladung we think Beego 1.x is more stable. Beego 2.x is not well maintained given Beego community inacitivity. If there are bugs, we intend to fork Beego 1.x and fix it by ourselves.

If you have other questsion, create new issue, don't append this one

**Pull request closed without merging**
