### PR TITLE
feat: add OSON SMS provider

### PR DESCRIPTION
**Pull request by waffle-frame**
"[Oson SMS](https://osonsms.com/)" provider is one of the SMS gateways throughout Tajikistan

I also implemented the logic for working with the provider for the backend.
[Link](https://github.com/casdoor/go-sms-sender/pull/39) for defailt

### CODE REVIEW

**Comment by hsluoyz** [comment]
@waffle-frame you need to add the Go backend code, including updating oss package version. Or it won't work

**Comment by waffle-frame** [comment]
@hsluoyz 

On my test environment I first forked [casdoor/go-sms-sender](https://github.com/casdoor/go-sms-sender), then made changes to the code, adding a new [provider](https://github.com/casdoor/go-sms-sender/pull/39). 
After that, I forked the [Casdoor](https://github.com/casdoor/casdoor) repository. and used [waffle-frame/go-sms-sender](https://github.com/waffle-frame/go-sms-sender) repo for testing.

Everything worked successfully

image_2024-03-03_20-58-57

image_2024-03-03_21-00-53


Can you please explain what exactly I need to do?

**Comment by hsluoyz** [comment]
@waffle-frame you didn't add all commits in your fork to this PR, see: https://github.com/waffle-frame/casdoor/commits/master/

image

**Comment by waffle-frame** [comment]
@hsluoyz That's right, that's how it should be.

There are no files in the [casdoor](https://github.com/casdoor/casdoor/) that should be subject to change, since I only implemented changes for [SMS providers](https://github.com/casdoor/go-sms-sender). 

The route of SMS providers, in turn, has an interface to satisfy, which is implemented in the casdoor/go-sms-sender. Accordingly, there is no need to change the files in this current repository

**Comment by waffle-frame** [comment]
@hsluoyz 

Here I am doing a search through the casdoor files, which is located on my local machine. The Infobip SMS provider is only available in 2 js files. Logic for operation The provider login is located in [casdoor/go-sms-sender/infobip.go](https://github.com/casdoor/go-sms-sender/blob/master/infobip.go)

I also implemented the logic for the oson sms provider, you [approved](https://github.com/casdoor/go-sms-sender/pull/39) it a few hours ago

image

**Comment by hsluoyz** [comment]
@waffle-frame I'm talking about: https://github.com/casdoor/casdoor/commit/8b64d113fb38c0c27ca38ed256bf84a74684804a , resolved now

**Pull request merged**
