### PR TITLE
feat: container image build ci for push image to github registry

### PR DESCRIPTION
**Pull request by Rajpratik71**
Use GitHub CI to build the latest Container image on git push and store container image on GitHub registry

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz review

**Review by ComradeProgrammer — COMMENTED** [review]
Well, maybe there is something more for you to do. If you read our dockerfile or build.yml , you would have found that actually, we have two images, one of them is normal image, and the other one is called "all-in-one". Please follow the naming convention in  the build.yml for github workflow and enable both images to be pushed into ghcr

**Comment by nodece** [comment]
You only need to improve the build.yml workflow to push the docker image to `ghcr.io`.

**Review by rafaelgfirmino — CHANGES_REQUESTED** [review]

**Comment by hsluoyz** [comment]
DockerHub for now is enough.

**Pull request closed without merging**
