### PR TITLE
feat: add the missing userId param docs for get-user API

### PR DESCRIPTION
**Pull request by zzjin**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@zzjin plz fix conflicts and don't contain other people's commits:

image

**Comment by zzjin** [comment]
> @zzjin plz fix conflicts and don't contain other people's commits:
> 
> image

done.

**Comment by hsluoyz** [comment]
@zzjin plz fix conflict again

**Comment by zzjin** [comment]
Thanks merge.
So strange, I dont push any commit anymore, but there shows conflicts?

**Pull request merged**
