### PR TITLE
fix: fix all frontend warnings

### PR DESCRIPTION
**Pull request by joy0010**
Fix: https://github.com/casdoor/casdoor/issues/958

I simply removed those unused parameters.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@qianxi0410

**Comment by qianxi0410** [comment]
In fact, now we do not report errors and warnings for unused parameters. This pr of yours is most likely out of date.
@joy0010 

#983 This pr has fixed the bug in #958

**Comment by hsluoyz** [comment]
Already fixed by: https://github.com/casdoor/casdoor/pull/983

**Comment by joy0010** [comment]
> In fact, now we do not report errors and warnings for unused parameters. This pr of yours is most likely out of date. @joy0010
> 
> #983 This pr has fixed the bug in #958

Got it.

**Pull request closed without merging**
