### PR TITLE
fix: added refresh_token item to the grantTypes list (ApplicationEditPage.js)

### PR DESCRIPTION
**Pull request by Kalinin-Andrey**
Fix: https://github.com/casdoor/casdoor/issues/529#issuecomment-1116465026

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Kalinin-Andrey plz fix:

image

**Comment by Kalinin-Andrey** [comment]
@Abingcbc, @ComradeProgrammer, @seriouszyx, @Steve0x2a, please review, it's only one line. ))

**Comment by hsluoyz** [comment]
@Kalinin-Andrey hi, plz sign the CLA:

image

**Comment by nomeguy** [comment]
Fixed in: https://github.com/casdoor/casdoor/commit/1c949e415ea84a162366e855bc4397eda32d1a9e

**Pull request closed without merging**
