### PR TITLE
feat: add arm docker support

### PR DESCRIPTION
**Pull request by WarlockFish**
`build.sh` shell rdedirect is  invalid 。
add arm64 and armv7  docker, use qemu and compilation arm time  is long(about 40 min  ),because the [yarn or node bug](https://github.com/yarnpkg/yarn/issues/5259)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@WarlockFish plz fix:

image

**Comment by hsluoyz** [comment]
@ComradeProgrammer @seriouszyx @Resulte plz review

**Comment by hsluoyz** [comment]
Hi @WarlockFish , what does this PR add? Does it add Arm-related image files to the Docker image to increase the image size? I'd like to know all side effects brought by this PR

/cc @Abingcbc 

@ComradeProgrammer @wenxuan70

**Comment by WarlockFish** [comment]
@hsluoyz   it see like [docker hub](https://hub.docker.com/r/fish3/casdoor/tags),  i test  tag v0.0.0 is ok in arm。the images for  framework  is  separated 。

**Comment by hsluoyz** [comment]
@WarlockFish so it will generate addtional images, right? I ask this because our DockerHub plan is limited in storage. If we take up too much space in DockerHub, Docker will throttle us or even block us before the next due date.

**Comment by WarlockFish** [comment]
@hsluoyz ok，i will use my docker images

**Pull request closed without merging**
