### PR TITLE
feat: Update adapter.go to support all db drivers

### PR DESCRIPTION
**Pull request by zzjin**
Signed-off-by: zzjin <tczzjin@gmail.com>

### Docker image diff:
|REPOSITORY|TAG|IMAGE ID|CREATED|SIZE|
|---|---|---|---|---|
|casdoor          |  origin  |    923721c86eb4  | 2 minutes ago |  540MB| 
|casdoor          |  full      |  157b49386bdc  | 1 minutes ago |  541MB|

### Explain
The codebase already have `pgsql`+`mssql` required `indirect`, as we just change `indirect` require module to `direct`, the end package size is not increased. 

Closes: #937

### CODE REVIEW

**Comment by nomeguy** [comment]
Done by: https://github.com/casdoor/casdoor/commit/d55ae7d1d2a9221dea3be80911c68eb9a275c3d0

**Comment by WarlockFish** [comment]
> Done by: [d55ae7d](https://github.com/casdoor/casdoor/commit/d55ae7d1d2a9221dea3be80911c68eb9a275c3d0)

why not open sqlite3？

**Comment by zzjin** [comment]
Why not open sqlite3？

**Comment by nomeguy** [comment]
Hi @zzjin your PR has carried some unexpected changes like:

image

Because it's so simple change so I just committed instead of letting you re-work on it. I hope you don't mind it :)

For sqlite3, this is because `github.com/mattn/go-sqlite3` is a cgo package, which requires gcc and even causes compiling error in Windows. In another word, with this change, Casdoor cannot be built in vanilla Windows any more, which will cause too much trouble for us. Any other good solutions to resolve this are welcome!

image

**Comment by zzjin** [comment]
OK. Got It.

**Pull request closed without merging**
