### PR TITLE
feat: Allow to sign up with Email without verification

### PR DESCRIPTION
**Pull request by Resulte**
Fix: https://github.com/casdoor/casdoor/issues/722 
We can remove Email verification in signup page by configuring the application edit page.

Screen Shot 2022-05-02 at 15 19 29

### CODE REVIEW

**Comment by Resulte** [comment]
One problem I have is that for previously created applications, they do not have the Email code field, so by default they will disable Email verification for previously created applications. Is this appropriate? Or should I set it in reverse, such as hidenEmailCode?

**Comment by hsluoyz** [comment]
@Resulte 

image

**Comment by Resulte** [comment]
> @Resulte
> 
> image

@hsluoyz I finished this.

**Comment by hsluoyz** [comment]
@Resulte demo site or video?

**Comment by Resulte** [comment]
> @Resulte demo site or video?

@hsluoyz The video is below.

https://user-images.githubusercontent.com/34178764/166208182-f91affc9-486d-4c9a-a519-bba465e02bef.mp4

**Pull request merged**
