### PR TITLE
feat: fix login with password bug when feature is disabled

### PR DESCRIPTION
**Pull request by notdu**
Prevent users from logging in with a password through the API when the login with password feature is disabled. 
This enhances security on the backend server.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@notdu fix:

image

**Comment by notdu** [comment]
@hsluoyz fixed, help me to check it again.

**Comment by hsluoyz** [comment]
@notdu your GitHub user and commit author should be the same person, this is why the CLA doesn't pass

image

**Comment by notdu** [comment]
@hsluoyz, i fixed it
Thanks

**Pull request merged**
