### PR TITLE
feat: rename all publicKey occurrences to certificate

### PR DESCRIPTION
**Pull request by FoeverA0**
Fix: https://github.com/casdoor/casdoor/issues/585

Replace the variable names publicKey and PublicKey with certificat and Certificat respectively (because the certificate variable originally existed)，resolve the issue of certificate and public key confusion

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Abingcbc @seriouszyx @Resulte @RyaoChengfeng  plz review

**Comment by hsluoyz** [comment]
@seriouszyx @Abingcbc plz review

**Comment by Abingcbc** [comment]
LGTM

**Review by seriouszyx — APPROVED** [review]
LGTM. Thanks for your contribution! 
I noticed that the column name changed: `publicKey` --> `certificate`. So after this PR, the certificate's content previously created is empty as below.

previously created cert (abnormal):

image

new cert (looks good):

image

We need to do something to prevent user confusion, such as compatibility with the previous column or adding documentation to explain.

**Pull request merged**
