### PR TITLE
fix: fix method for oauth

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
fix: fix method for oauth

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Steve0x2a @seriouszyx is this method good? Plz review

**Comment by aecra** [comment]
This is not a good way to fix oauth.

For example, access_token should only accept POST request. For OPTION request, there should be a signal func to return cors response. It is bad to execute POST func for OPTION.

And it is better to add an domain field to every application to verify OPTION request.

**Comment by hsluoyz** [comment]
@aecra can you make a PR?

**Comment by aecra** [comment]
@hsluoyz I can solve next week.

**Comment by aecra** [comment]
#826

**Pull request closed without merging**
