### PR TITLE
feat: make redirectUri token param follow OAuth2 standard

### PR DESCRIPTION
**Pull request by joezhang-sh**
Fix: https://github.com/casdoor/casdoor/issues/1793

1. rename "token" to "access_token" #1793 
2. change "?" to "&" #1012 
 
I will update the relevant document in [casdoor-website](https://github.com/casdoor/casdoor-website) when the PR is merged.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@joezhang-sh fix:

image

**Comment by joezhang-sh** [comment]
> 

Hi @hsluoyz, done

**Comment by hsluoyz** [comment]
@leo220yuyaodog

**Comment by hsluoyz** [comment]
@joezhang-sh plz update docs

**Pull request merged**
