### PR TITLE
feat: Add bootstrap support for groups, adapters and enforcers

### LINKED ISSUE #2606: Support initial import of more object types
Hi there! Thanks for your awesome work. I am positively surprised by how easy it is to bootstrap Casbin.

The data is very easy to obtain via Swagger, as such I assumed I would be able to also import the following objects via `inital_data.json`:

- Groups
- Adapters
- Enforcers

### PR DESCRIPTION
**Pull request by SchoolGuy**
This PR will add - once marked ready - support for importing groups, adapters and enforcers via the `inital_data.json` file.

Fixes #2606

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Not a fan of signing CLAs but I understand it from a business perspective...

**Comment by hsluoyz** [comment]
@SchoolGuy has this been ready?

**Comment by SchoolGuy** [comment]
@hsluoyz No that's why I used a draft PR.

**Comment by hsluoyz** [comment]
@SchoolGuy any update?

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor/pull/2685

**Comment by SchoolGuy** [comment]
Sorry that I was too slow. I was distracted by other PRs I have open atm.

**Pull request closed without merging**
