### PR TITLE
fix: security verification

### PR DESCRIPTION
**Pull request by cnjinhy**
security verification

### CODE REVIEW

**Comment by leo220yuyaodog** [comment]
@cnjinhy Hi, thanks for your contribution. But I have some confusion. Even if you get the code,  the code does not contain any information. You need to use the code to exchange accessToken. When your call the api `/login/oauth/access_token`, the `client_secret` is required. So it seems not necessary to verify client_secret` in this api.

**Comment by cnjinhy** [comment]
> @cnjinhy Hi, thanks for your contribution. But I have some confusion. Even if you get the code, the code does not contain any information. You need to use the code to exchange accessToken. When your call the api `/login/oauth/access_token`, the `client_secret` is required. So it seems not necessary to verify client_secret` in this api. Can you provide more details about the Security verification

Anyone who only knows the username and clientId can obtain the **code** of any other user through this interface, and then exchange the **code** for access to the application's callback **address_token** to log in to the application; 
In theory, this interface can only obtain code after user authorization, or be used as an internal network service for server calls, rather than being exposed in the public network

**Comment by leo220yuyaodog** [comment]
@cnjinhy lgtm 
plz fix the ci 
image

**Comment by cnjinhy** [comment]
how to fix the "File is not `gofumpt`-ed (gofumpt)" error? 
I use gofmt , but it not works;

**Comment by leo220yuyaodog** [comment]
> gofumpt

You need to  use [gofumpt](https://github.com/mvdan/gofumpt). It is more stricter than gofmt.

**Comment by cnjinhy** [comment]
why e2e-test failed？ I don‘t change the file

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor/commit/ee8c2650c3e50e95f75574e6d31334a67207db90 (reverts: https://github.com/casdoor/casdoor/commit/54ef2ec09fd3c767da7582f8dd6a90c2b076a96e)

**Comment by cnjinhy** [comment]
> Fixed by: [ee8c265](https://github.com/casdoor/casdoor/commit/ee8c2650c3e50e95f75574e6d31334a67207db90) (reverts: [54ef2ec](https://github.com/casdoor/casdoor/commit/54ef2ec09fd3c767da7582f8dd6a90c2b076a96e))

Remove this API, it cannot be used as a backend for microservices, and it is also not compatible downwards

**Pull request closed without merging**
