### PR TITLE
feat: add implicit flow support

### PR DESCRIPTION
**Pull request by Steve0x2a**
1. add implicit flow support
  access `/login/oauth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=token&scope=openid+email+profile&state=1233` to get accesstoken and redirect to `REDIRECT_URI/#token=ACCESS_TOKEN`
2. add id_token response_type support
    access `/login/oauth/authorize?client_id=CLIENT_ID&redirect_uri=REDIRECT_URI&response_type=id_token&scope=openid+email+profile&state=1233` to get accesstoken and redirect to `REDIRECT_URI/#id_token=ID_TOKEN` 
 Fix: https://github.com/casdoor/casdoor/issues/514

Signed-off-by: Steve0x2a <stevesough@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@LeonDevLifeLog plz review

**Comment by LeonDevLifeLog** [comment]
> @LeonDevLifeLog plz review

I will test it tomorrow.

**Comment by LeonDevLifeLog** [comment]
> @LeonDevLifeLog you mean adding it to our docs like this one: https://casdoor.org/docs/integration/apisix ? Thanks!

Yes, you're welcome.

**Comment by Steve0x2a** [comment]
@LeonDevLifeLog Okay, I will modify and test according to the documentation. Thanks for your help.

**Comment by Steve0x2a** [comment]
@LeonDevLifeLog 
When we use response_mode=fragment, the parameters are not sent directly to the server, so they are not visible when we grab the packet. I tested locally by setting redirect_uri to localhost, which redirects to http://localhost/#id_token=eyJ... So I think our fragment implementation should be fine, but Huawei IAM will send a post:https://auth.huaweicloud.com/authui/oidc/post after redirect, which is the endpoint of form_post, so I don't know what's wrong with it

I will try to give casdoor to implement the response_mode of form_post

**Pull request merged**
