### PR TITLE
fix: wrong Vietnam country code.

### PR DESCRIPTION
**Pull request by saosangmo**
Sorry, it is my mistake. I make PR to revert language code for Vietnamese package. 
(The only place to edit is country code in `web/src/Setting.js`)
 `{label: "TiếngViệt", key: "vi", country: "VI", alt: "TiếngViệt"},` => `...country: "VN"...`

### CODE REVIEW

**Comment by hsluoyz** [comment]
@saosangmo why change back to "vi"? Isn't the correct string "vn"?

**Comment by hsluoyz** [comment]
@saosangmo I think you have missed a lot of places, like: 

I suggest you searching all patterns like zh-cn. It's similar to vi-vn. Search all "zh" and "cn", you will know where to replace

image

**Comment by saosangmo** [comment]
@hsluoyz done.

**Comment by hsluoyz** [comment]
@saosangmo

1. Did you search all "zh" and check your language code is "vi"?
2. Did you search all "cn" and check your country code is "vn"?

Provide two screenshots in Find window to make sure you have done it

**Comment by saosangmo** [comment]
@hsluoyz Very sorry, because I have not update PR. Please review it for me.

Screen Shot 2023-04-11 at 19 24 24
Screen Shot 2023-04-11 at 19 28 15

**Comment by hsluoyz** [comment]
@saosangmo did you really check all as I said? So why is the file in your screenshot not in the PR? 

image

**Pull request closed without merging**
