### PR TITLE
feat: replace response json by responseOk

### PR DESCRIPTION
**Pull request by thanhtinhpas1**
Fix issue [1641](https://github.com/casdoor/casdoor/issues/1641)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@thanhtinhpas1 plz fix:

image

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 plz fix:
> 
> image
> 

That's because UI error, this MR still missing UI implement.

Can you take a quick look at BE changes first?

**Comment by hsluoyz** [comment]
@thanhtinhpas1 the backend code looks good to me

**Comment by thanhtinhpas1** [comment]
> @thanhtinhpas1 the backend code looks good to me

Will add UI implement and go casdoor sdk today.

**Comment by aegoroff** [comment]
It may break all SDKs

**Comment by hsluoyz** [comment]
@thanhtinhpas1 any update?

**Pull request closed without merging**
