### PR TITLE
ci: split the build workflow and fix push the docker image

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ComradeProgrammer plz review

**Review by ComradeProgrammer — COMMENTED** [review]
Well I do have some questions(or confusions).

0. What kind of bug have you encountered, which make you proposed this pr?
1. "if: github.repository == 'casdoor/casdoor' && github.event_name == 'push'"should be preserved I think, otherwise the CI would be triggered in your forked repository, lead to a failure in CI.
2. The original demand is that the "pushing image to remote should only be triggered when secondary version name changed", for example, the version number changing from 1.0.0 to 1.1.0 is supposed to trigger a push, however, its changing from 1.1.0 to 1.1.1 is not supposed to trigger a push. However, using semantic-release directly will case a push every time the version number is changed. Our resources on github and docker hub are limited so we cannot let so many versions consume them.

**Comment by nodece** [comment]
1. The GitHub Action doesn't automatically run on the fork repo, see: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
2. We should always bump this software when the PR is merged into the master branch, and I feel that the current resources are sufficient on Github Action and DockerHub.

**Comment by ComradeProgrammer** [comment]
> 1. The GitHub Action doesn't automatically run on the fork repo, see: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> 2. We should always bump this software when the PR is merged into the master branch, and I feel that the current resources are sufficient on Github Action and DockerHub.

1. Developer may switch on the CI in order to run tests( although we don't have one yet ), so I think is useful to prohibit the pushing behavior from being proceeded under such circumstance
2. @hsluoyz plz decide whether the demand should be altered

**Comment by nodece** [comment]
> Developer may switch on the CI in order to run tests( although we don't have one yet ), so I think is useful to prohibit the pushing behavior from being proceeded under such circumstance

I agreed with you.

**Comment by hsluoyz** [comment]
> The original demand is that the "pushing image to remote should only be triggered when secondary version name changed", for example, the version number changing from 1.0.0 to 1.1.0 is supposed to trigger a push, however, its changing from 1.1.0 to 1.1.1 is not supposed to trigger a push. However, using semantic-release directly will case a push every time the version number is changed. Our resources on github and docker hub are limited so we cannot let so many versions consume them.

Yes. This is the result of discussion. We don't release for revision update.

**Pull request closed without merging**
