### PR TITLE
fix: fix Social Signup or Linking causes 500 Internal Server Error

### PR DESCRIPTION
**Pull request by qianxi0410**
Fix: #918

### CODE REVIEW

**Comment by qianxi0410** [comment]
plz r @hsluoyz

**Comment by hsluoyz** [comment]
@KrishnaPG plz check if this PR can fix your issue

**Comment by KrishnaPG** [comment]
Thank you much @hsluoyz . We are running casdoor as `standard docker image`
```
docker run  -p 8000:8000 -v /path/to/app.conf:/conf casbin/casdoor:latest
```
How to access this PR as part of the standard docker image?

**Comment by hsluoyz** [comment]
@KrishnaPG the "fix: xxx" PR won't trigger a new Docker image release. It seems that you need to wait for `1.76.0` release

**Comment by KrishnaPG** [comment]
Understood. Thank you @hsluoyz Hope, it wont be too long. On the docker hub, I see the [releases](https://hub.docker.com/r/casbin/casdoor/tags) every few days frequently. Hopefully `1.76.0` will be soon

**Pull request merged**
