### PR TITLE
fix(controller): add check when deleting a user

### PR DESCRIPTION
**Pull request by xtlsoft**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@xtlsoft can you explain the PR?

**Comment by xtlsoft** [comment]
Previously no proper permission check was done when deleting a user. I could delete an admin user with a normal user.

**Comment by hsluoyz** [comment]
@xtlsoft usually normal users cannot delete users. All `built-in` org users are global admins, see: https://casdoor.org/docs/basic/core-concepts#how-does-casdoor-manage-itself

**Comment by xtlsoft** [comment]
Thx. I'm so sorry for bothering you.

**Pull request closed without merging**
