### PR TITLE
fix: fix missing username in forgetpage

### LINKED ISSUE #483: Retrieve password error: unknown authentication type (not password or provider)
Hello, everyone!

I am just a beginner with casdoor.
I am trying to test a retrieve password, but received this error:
```
unknown authentication type (not password or provider), form = {
	"type": "login",
	"organization": "org",
	"username": "",
	"password": "",
	"name": "",
	"email": "",
	"phone": "",
	"affiliation": "",
	"idCard": "",
	"region": "",
	"application": "socbazar",
	"provider": "",
	"code": "38316",
	"state": "",
	"redirectUri": "",
	"method": "",
	"emailCode": "",
	"phoneCode": "",
	"phonePrefix": "7",
	"autoSignin": false,
	"relayState": "",
	"samlResponse": ""
}
```
The username is found and the email substituted in the form field, but they are not sent to the server.
Email provider is configured and working.

What I am doing wrong?

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
fix: fix missing username in forgetpage
FIX #483

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Kalinin-Andrey plz review

**Comment by hsluoyz** [comment]
@ComradeProgrammer demo link?

**Comment by hsluoyz** [comment]
@ComradeProgrammer why the demo shows this?

image

**Comment by Kalinin-Andrey** [comment]
> @Kalinin-Andrey plz review

@ComradeProgrammer , @hsluoyz 

Yes, it worked!
Merge, please, in the main repository.
Thank you very much!

**Pull request merged**
