### PR TITLE
feat: add the ability to use the application for several organizations

### PR DESCRIPTION
**Pull request by waffle-frame**
Ref #2821

### CODE REVIEW

**Comment by dacongda** [comment]
`err := ormer.Engine.Desc("created_time").Find(&applications, &Application{Organization: organization})`

maybe it is better to add a where clause in this query to find public application?

**Comment by waffle-frame** [comment]
> `err := ormer.Engine.Desc("created_time").Find(&applications, &Application{Organization: organization})`
> 
> может быть, лучше добавить в этот запрос предложениеwhere, чтобы найти общедоступное применение?

Yes, you are right, good point
What do you think about the implementation?

**Comment by dacongda** [comment]
if you mean the implementation, you can refer to
https://github.com/casdoor/casdoor/blob/3354945119ba1202b5f889a461635926a76716a6/object/provider.go#L122

**Comment by maknahar** [comment]
Any update on this PR getting merged. We need this as well.

**Comment by dacongda** [comment]
> Any update on this PR getting merged. We need this as well.

we have already add this future in #3108

**Comment by dacongda** [comment]
> Any update on this PR getting merged. We need this as well.

you can check out `https://casdoor.org/docs/application/shared-application/` for more detail about shared application

**Comment by maknahar** [comment]
Thank you for the quick response. I will check it out @dacongda .

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/casdoor/casdoor/pull/3108

**Pull request closed without merging**
