### PR TITLE
fix: Docker compose on Apple M1 Chip

### PR DESCRIPTION
**Pull request by muharihar**
fix error:
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

### CODE REVIEW

**Comment by hsluoyz** [comment]
@muharihar hi, plz fix:

image

**Comment by muharihar** [comment]
> @muharihar hi, plz fix:
> 
> image

@hsluoyz  Done, "fix:"

**Comment by hsluoyz** [comment]
image

**Comment by hsluoyz** [comment]
@muharihar plz fix both issues

**Comment by hsluoyz** [comment]
Done at: https://github.com/casdoor/casdoor/commit/b424937ae46862f1eb97f331c46aeec7f61d0251

**Pull request closed without merging**
