### PR TITLE
feat: AI responses support streaming

### PR DESCRIPTION
**Pull request by 1307super**
Is an AI response that supports streaming return

### CODE REVIEW

**Comment by hsluoyz** [comment]
@1307super please paste a video here to show that the streaming works

**Comment by 1307super** [comment]
> @1307super please paste a video here to show that the streaming works

Since I don't have an openai account, the content is returned by the mock openai interface


https://github.com/casdoor/casdoor/assets/35326304/6f6589af-e22c-4e86-b8a8-3157be413b76

**Comment by hsluoyz** [comment]
@1307super can you add this mock openai interface to the code as a new "type" option of provider? The mock AI provider is useful to the project. Moreover, I cannot see the "streaming" with the real openai API. So I also need to test your mock openai interface.

**Comment by 1307super** [comment]
> @1307super the video looks good. Can you add this mock openai interface to the code as a new "type" option of provider? The mock AI provider is useful to the project. Moreover, I cannot see the "streaming" with the real openai API. So I also need to test your mock openai interface.

In fact, the data I simulated was only fixed in the interface and not called the API

Here is the code

```golang
flusher, ok := writer.(http.Flusher)
if !ok {
  return fmt.Errorf("writer does not implement http.Flusher")
}
text := "mock data"
for _, v := range text {
  if _, err := fmt.Fprintf(writer, "data: %s\n\n", string(v)); err != nil {
	  return err
  }
  flusher.Flush()
  time.Sleep(200 * time.Millisecond)
}
```

**Pull request merged**
